#baseURL = "https://division.byzero.de"
baseURL = "https://eloquent-hamilton-d5c4ce.netlify.com"
languageCode = "en-us"
defaultContentLanguage = "en"
title = "muhh streamt"
theme = "papercss-hugo-theme"
#googleAnalytics = "UA-123456789-1"

[taxonomies]
  tag = "tags"

[permalinks]
  post = "/:filename/"

[imaging]
  quality = 99

[params]
  homeMetaContent = "A website for a devops person's livestream"
  # For more date formats see https://gohugo.io/functions/format/
  dateFormat = "January 2, 2006"

[menu]
#  [[menu.nav]]
#    name = "Blog"
#    url = "/"
#    weight = 0
#  [[menu.nav]]
#    name = "Tags"
#    url = "/tags/"
#    weight = 2
  [[menu.nav]]
    name = "About"
    url = "/about/"
    weight = 3
  [[menu.nav]]
    name = "RSS"
    url = "/index.xml"
    weight = 4
